#Setting:
#Expiration         --> 本地文件超时时间
#CheckExpiration    --> 检查本地文件是否超时的频率
#Common             --> 本地存放Module的路径

#Database:
#Host               --> 数据库主机地址
#Port               --> 数据库主机端口
#Username           --> 用户名
#Password           --> 密码

#GRPC:
#Port               --> GRPC服务使用的端口

#Backup:
#Host               --> 备份服务器的GRPC主机地址
#Port               --> 备份服务器的GRPC端口号


Setting:
  # Day
  Expiration: 180
  # Second
  CheckUnwanted: 500
  CheckExpiration: 10
  CheckClientExpiration: 10
  Common: E:\Server\Common


Database:
  Host: localhost
  Port: 3306
  Username: root
  Password: Qaqaqa00.0

GRPC:
  Port: 9998

Backup:
  - Host: localhost
    Port: 9999

  - Host: 10.60.230.12
    Port: 9999

  - Host: 10.230.230.44
    Port: 9999