// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: grpc/ModuleBalancing.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StorerecordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Heartbeat     string                 `protobuf:"bytes,1,opt,name=heartbeat,proto3" json:"heartbeat,omitempty"`
	Serveraddress string                 `protobuf:"bytes,2,opt,name=Serveraddress,proto3" json:"Serveraddress,omitempty"`
	Partnumber    string                 `protobuf:"bytes,3,opt,name=partnumber,proto3" json:"partnumber,omitempty"`
	Modulenames   []string               `protobuf:"bytes,4,rep,name=modulenames,proto3" json:"modulenames,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StorerecordRequest) Reset() {
	*x = StorerecordRequest{}
	mi := &file_grpc_ModuleBalancing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorerecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorerecordRequest) ProtoMessage() {}

func (x *StorerecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_ModuleBalancing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorerecordRequest.ProtoReflect.Descriptor instead.
func (*StorerecordRequest) Descriptor() ([]byte, []int) {
	return file_grpc_ModuleBalancing_proto_rawDescGZIP(), []int{0}
}

func (x *StorerecordRequest) GetHeartbeat() string {
	if x != nil {
		return x.Heartbeat
	}
	return ""
}

func (x *StorerecordRequest) GetServeraddress() string {
	if x != nil {
		return x.Serveraddress
	}
	return ""
}

func (x *StorerecordRequest) GetPartnumber() string {
	if x != nil {
		return x.Partnumber
	}
	return ""
}

func (x *StorerecordRequest) GetModulenames() []string {
	if x != nil {
		return x.Modulenames
	}
	return nil
}

type StorerecordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Isok          bool                   `protobuf:"varint,1,opt,name=isok,proto3" json:"isok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StorerecordResponse) Reset() {
	*x = StorerecordResponse{}
	mi := &file_grpc_ModuleBalancing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorerecordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorerecordResponse) ProtoMessage() {}

func (x *StorerecordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_ModuleBalancing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorerecordResponse.ProtoReflect.Descriptor instead.
func (*StorerecordResponse) Descriptor() ([]byte, []int) {
	return file_grpc_ModuleBalancing_proto_rawDescGZIP(), []int{1}
}

func (x *StorerecordResponse) GetIsok() bool {
	if x != nil {
		return x.Isok
	}
	return false
}

type ModuleDownloadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=Filename,proto3" json:"Filename,omitempty"`
	Offset        int64                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModuleDownloadRequest) Reset() {
	*x = ModuleDownloadRequest{}
	mi := &file_grpc_ModuleBalancing_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModuleDownloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModuleDownloadRequest) ProtoMessage() {}

func (x *ModuleDownloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_ModuleBalancing_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModuleDownloadRequest.ProtoReflect.Descriptor instead.
func (*ModuleDownloadRequest) Descriptor() ([]byte, []int) {
	return file_grpc_ModuleBalancing_proto_rawDescGZIP(), []int{2}
}

func (x *ModuleDownloadRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *ModuleDownloadRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ModuleDownloadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       []byte                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Completed     bool                   `protobuf:"varint,3,opt,name=completed,proto3" json:"completed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModuleDownloadResponse) Reset() {
	*x = ModuleDownloadResponse{}
	mi := &file_grpc_ModuleBalancing_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModuleDownloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModuleDownloadResponse) ProtoMessage() {}

func (x *ModuleDownloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_ModuleBalancing_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModuleDownloadResponse.ProtoReflect.Descriptor instead.
func (*ModuleDownloadResponse) Descriptor() ([]byte, []int) {
	return file_grpc_ModuleBalancing_proto_rawDescGZIP(), []int{3}
}

func (x *ModuleDownloadResponse) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *ModuleDownloadResponse) GetCompleted() bool {
	if x != nil {
		return x.Completed
	}
	return false
}

type FileInformation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MD5           string                 `protobuf:"bytes,5,opt,name=MD5,proto3" json:"MD5,omitempty"`
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Modify        int64                  `protobuf:"varint,3,opt,name=modify,proto3" json:"modify,omitempty"` // 修改时间 (Unix 时间戳)
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Create        int64                  `protobuf:"varint,4,opt,name=create,proto3" json:"create,omitempty"` // 创建时间 (Unix 时间戳 - 非所有文件系统都支持)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileInformation) Reset() {
	*x = FileInformation{}
	mi := &file_grpc_ModuleBalancing_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileInformation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileInformation) ProtoMessage() {}

func (x *FileInformation) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_ModuleBalancing_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileInformation.ProtoReflect.Descriptor instead.
func (*FileInformation) Descriptor() ([]byte, []int) {
	return file_grpc_ModuleBalancing_proto_rawDescGZIP(), []int{4}
}

func (x *FileInformation) GetMD5() string {
	if x != nil {
		return x.MD5
	}
	return ""
}

func (x *FileInformation) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileInformation) GetModify() int64 {
	if x != nil {
		return x.Modify
	}
	return 0
}

func (x *FileInformation) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *FileInformation) GetCreate() int64 {
	if x != nil {
		return x.Create
	}
	return 0
}

type AnalyzingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Fbytes        []byte                 `protobuf:"bytes,2,opt,name=fbytes,proto3" json:"fbytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzingRequest) Reset() {
	*x = AnalyzingRequest{}
	mi := &file_grpc_ModuleBalancing_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzingRequest) ProtoMessage() {}

func (x *AnalyzingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_ModuleBalancing_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzingRequest.ProtoReflect.Descriptor instead.
func (*AnalyzingRequest) Descriptor() ([]byte, []int) {
	return file_grpc_ModuleBalancing_proto_rawDescGZIP(), []int{5}
}

func (x *AnalyzingRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *AnalyzingRequest) GetFbytes() []byte {
	if x != nil {
		return x.Fbytes
	}
	return nil
}

type AnalyzingResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Modulename     []string               `protobuf:"bytes,1,rep,name=modulename,proto3" json:"modulename,omitempty"`
	Analyzingerror []string               `protobuf:"bytes,2,rep,name=analyzingerror,proto3" json:"analyzingerror,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AnalyzingResponse) Reset() {
	*x = AnalyzingResponse{}
	mi := &file_grpc_ModuleBalancing_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzingResponse) ProtoMessage() {}

func (x *AnalyzingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_ModuleBalancing_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzingResponse.ProtoReflect.Descriptor instead.
func (*AnalyzingResponse) Descriptor() ([]byte, []int) {
	return file_grpc_ModuleBalancing_proto_rawDescGZIP(), []int{6}
}

func (x *AnalyzingResponse) GetModulename() []string {
	if x != nil {
		return x.Modulename
	}
	return nil
}

func (x *AnalyzingResponse) GetAnalyzingerror() []string {
	if x != nil {
		return x.Analyzingerror
	}
	return nil
}

type ExpirationPushRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Serveraddress    string                 `protobuf:"bytes,1,opt,name=serveraddress,proto3" json:"serveraddress,omitempty"`
	Maxretentiondays int64                  `protobuf:"varint,2,opt,name=maxretentiondays,proto3" json:"maxretentiondays,omitempty"`
	Checkdir         string                 `protobuf:"bytes,3,opt,name=checkdir,proto3" json:"checkdir,omitempty"`
	Outdir           string                 `protobuf:"bytes,4,opt,name=outdir,proto3" json:"outdir,omitempty"`
	Backdir          string                 `protobuf:"bytes,5,opt,name=backdir,proto3" json:"backdir,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ExpirationPushRequest) Reset() {
	*x = ExpirationPushRequest{}
	mi := &file_grpc_ModuleBalancing_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpirationPushRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpirationPushRequest) ProtoMessage() {}

func (x *ExpirationPushRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_ModuleBalancing_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpirationPushRequest.ProtoReflect.Descriptor instead.
func (*ExpirationPushRequest) Descriptor() ([]byte, []int) {
	return file_grpc_ModuleBalancing_proto_rawDescGZIP(), []int{7}
}

func (x *ExpirationPushRequest) GetServeraddress() string {
	if x != nil {
		return x.Serveraddress
	}
	return ""
}

func (x *ExpirationPushRequest) GetMaxretentiondays() int64 {
	if x != nil {
		return x.Maxretentiondays
	}
	return 0
}

func (x *ExpirationPushRequest) GetCheckdir() string {
	if x != nil {
		return x.Checkdir
	}
	return ""
}

func (x *ExpirationPushRequest) GetOutdir() string {
	if x != nil {
		return x.Outdir
	}
	return ""
}

func (x *ExpirationPushRequest) GetBackdir() string {
	if x != nil {
		return x.Backdir
	}
	return ""
}

type ExpirationPushResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Partnumber    string                 `protobuf:"bytes,1,opt,name=partnumber,proto3" json:"partnumber,omitempty"`
	Modulename    []string               `protobuf:"bytes,2,rep,name=modulename,proto3" json:"modulename,omitempty"`
	Heartbeat     string                 `protobuf:"bytes,3,opt,name=heartbeat,proto3" json:"heartbeat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExpirationPushResponse) Reset() {
	*x = ExpirationPushResponse{}
	mi := &file_grpc_ModuleBalancing_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpirationPushResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpirationPushResponse) ProtoMessage() {}

func (x *ExpirationPushResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_ModuleBalancing_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpirationPushResponse.ProtoReflect.Descriptor instead.
func (*ExpirationPushResponse) Descriptor() ([]byte, []int) {
	return file_grpc_ModuleBalancing_proto_rawDescGZIP(), []int{8}
}

func (x *ExpirationPushResponse) GetPartnumber() string {
	if x != nil {
		return x.Partnumber
	}
	return ""
}

func (x *ExpirationPushResponse) GetModulename() []string {
	if x != nil {
		return x.Modulename
	}
	return nil
}

func (x *ExpirationPushResponse) GetHeartbeat() string {
	if x != nil {
		return x.Heartbeat
	}
	return ""
}

var File_grpc_ModuleBalancing_proto protoreflect.FileDescriptor

const file_grpc_ModuleBalancing_proto_rawDesc = "" +
	"\n" +
	"\x1agrpc/ModuleBalancing.proto\x12\x0fModuleBalancing\"\x9a\x01\n" +
	"\x12StorerecordRequest\x12\x1c\n" +
	"\theartbeat\x18\x01 \x01(\tR\theartbeat\x12$\n" +
	"\rServeraddress\x18\x02 \x01(\tR\rServeraddress\x12\x1e\n" +
	"\n" +
	"partnumber\x18\x03 \x01(\tR\n" +
	"partnumber\x12 \n" +
	"\vmodulenames\x18\x04 \x03(\tR\vmodulenames\")\n" +
	"\x13StorerecordResponse\x12\x12\n" +
	"\x04isok\x18\x01 \x01(\bR\x04isok\"K\n" +
	"\x15ModuleDownloadRequest\x12\x1a\n" +
	"\bFilename\x18\x01 \x01(\tR\bFilename\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\"P\n" +
	"\x16ModuleDownloadResponse\x12\x18\n" +
	"\acontent\x18\x04 \x01(\fR\acontent\x12\x1c\n" +
	"\tcompleted\x18\x03 \x01(\bR\tcompleted\"\x83\x01\n" +
	"\x0fFileInformation\x12\x10\n" +
	"\x03MD5\x18\x05 \x01(\tR\x03MD5\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\x12\x16\n" +
	"\x06modify\x18\x03 \x01(\x03R\x06modify\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x16\n" +
	"\x06create\x18\x04 \x01(\x03R\x06create\"F\n" +
	"\x10analyzingRequest\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x16\n" +
	"\x06fbytes\x18\x02 \x01(\fR\x06fbytes\"[\n" +
	"\x11analyzingResponse\x12\x1e\n" +
	"\n" +
	"modulename\x18\x01 \x03(\tR\n" +
	"modulename\x12&\n" +
	"\x0eanalyzingerror\x18\x02 \x03(\tR\x0eanalyzingerror\"\xb7\x01\n" +
	"\x15ExpirationPushRequest\x12$\n" +
	"\rserveraddress\x18\x01 \x01(\tR\rserveraddress\x12*\n" +
	"\x10maxretentiondays\x18\x02 \x01(\x03R\x10maxretentiondays\x12\x1a\n" +
	"\bcheckdir\x18\x03 \x01(\tR\bcheckdir\x12\x16\n" +
	"\x06outdir\x18\x04 \x01(\tR\x06outdir\x12\x18\n" +
	"\abackdir\x18\x05 \x01(\tR\abackdir\"v\n" +
	"\x16ExpirationPushResponse\x12\x1e\n" +
	"\n" +
	"partnumber\x18\x01 \x01(\tR\n" +
	"partnumber\x12\x1e\n" +
	"\n" +
	"modulename\x18\x02 \x03(\tR\n" +
	"modulename\x12\x1c\n" +
	"\theartbeat\x18\x03 \x01(\tR\theartbeat2\xbb\x01\n" +
	"\x06Module\x12]\n" +
	"\bDownload\x12&.ModuleBalancing.ModuleDownloadRequest\x1a'.ModuleBalancing.ModuleDownloadResponse0\x01\x12R\n" +
	"\tAnalyzing\x12!.ModuleBalancing.analyzingRequest\x1a\".ModuleBalancing.analyzingResponse2q\n" +
	"\x0eExpirationpush\x12_\n" +
	"\n" +
	"Expiration\x12&.ModuleBalancing.ExpirationPushRequest\x1a'.ModuleBalancing.ExpirationPushResponse0\x012o\n" +
	"\vStorerecord\x12`\n" +
	"\x11Updatestorerecord\x12#.ModuleBalancing.StorerecordRequest\x1a$.ModuleBalancing.StorerecordResponse(\x01B\aZ\x05/grpcb\x06proto3"

var (
	file_grpc_ModuleBalancing_proto_rawDescOnce sync.Once
	file_grpc_ModuleBalancing_proto_rawDescData []byte
)

func file_grpc_ModuleBalancing_proto_rawDescGZIP() []byte {
	file_grpc_ModuleBalancing_proto_rawDescOnce.Do(func() {
		file_grpc_ModuleBalancing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpc_ModuleBalancing_proto_rawDesc), len(file_grpc_ModuleBalancing_proto_rawDesc)))
	})
	return file_grpc_ModuleBalancing_proto_rawDescData
}

var file_grpc_ModuleBalancing_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_grpc_ModuleBalancing_proto_goTypes = []any{
	(*StorerecordRequest)(nil),     // 0: ModuleBalancing.StorerecordRequest
	(*StorerecordResponse)(nil),    // 1: ModuleBalancing.StorerecordResponse
	(*ModuleDownloadRequest)(nil),  // 2: ModuleBalancing.ModuleDownloadRequest
	(*ModuleDownloadResponse)(nil), // 3: ModuleBalancing.ModuleDownloadResponse
	(*FileInformation)(nil),        // 4: ModuleBalancing.FileInformation
	(*AnalyzingRequest)(nil),       // 5: ModuleBalancing.analyzingRequest
	(*AnalyzingResponse)(nil),      // 6: ModuleBalancing.analyzingResponse
	(*ExpirationPushRequest)(nil),  // 7: ModuleBalancing.ExpirationPushRequest
	(*ExpirationPushResponse)(nil), // 8: ModuleBalancing.ExpirationPushResponse
}
var file_grpc_ModuleBalancing_proto_depIdxs = []int32{
	2, // 0: ModuleBalancing.Module.Download:input_type -> ModuleBalancing.ModuleDownloadRequest
	5, // 1: ModuleBalancing.Module.Analyzing:input_type -> ModuleBalancing.analyzingRequest
	7, // 2: ModuleBalancing.Expirationpush.Expiration:input_type -> ModuleBalancing.ExpirationPushRequest
	0, // 3: ModuleBalancing.Storerecord.Updatestorerecord:input_type -> ModuleBalancing.StorerecordRequest
	3, // 4: ModuleBalancing.Module.Download:output_type -> ModuleBalancing.ModuleDownloadResponse
	6, // 5: ModuleBalancing.Module.Analyzing:output_type -> ModuleBalancing.analyzingResponse
	8, // 6: ModuleBalancing.Expirationpush.Expiration:output_type -> ModuleBalancing.ExpirationPushResponse
	1, // 7: ModuleBalancing.Storerecord.Updatestorerecord:output_type -> ModuleBalancing.StorerecordResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_grpc_ModuleBalancing_proto_init() }
func file_grpc_ModuleBalancing_proto_init() {
	if File_grpc_ModuleBalancing_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpc_ModuleBalancing_proto_rawDesc), len(file_grpc_ModuleBalancing_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_grpc_ModuleBalancing_proto_goTypes,
		DependencyIndexes: file_grpc_ModuleBalancing_proto_depIdxs,
		MessageInfos:      file_grpc_ModuleBalancing_proto_msgTypes,
	}.Build()
	File_grpc_ModuleBalancing_proto = out.File
	file_grpc_ModuleBalancing_proto_goTypes = nil
	file_grpc_ModuleBalancing_proto_depIdxs = nil
}
